import { SoundDefinition } from './soundTypes';

export const soundManifest: Record<string, SoundDefinition> = {
  task_started_01: {
    id: 'task_started_01',
    filePath: 'assets/office/sounds/task_started.wav',
    category: 'task_started',
    defaultVolume: 0.8,
    loop: false,
    priority: 'normal',
    cooldownPolicyMs: 500,
    maxSimultaneous: 2,
    accessibilityAlternative: 'Task started',
    placeholder: true,
    durationMs: 250,
  },
  task_completed_01: {
    id: 'task_completed_01',
    filePath: 'assets/office/sounds/task_completed.wav',
    category: 'task_completed',
    defaultVolume: 0.8,
    loop: false,
    priority: 'normal',
    cooldownPolicyMs: 500,
    maxSimultaneous: 2,
    accessibilityAlternative: 'Task completed successfully',
    placeholder: true,
    durationMs: 400,
  },
  task_paused_01: {
    id: 'task_paused_01',
    filePath: 'assets/office/sounds/task_paused.wav',
    category: 'task_paused',
    defaultVolume: 0.6,
    loop: false,
    priority: 'normal',
    cooldownPolicyMs: 1000,
    maxSimultaneous: 1,
    accessibilityAlternative: 'Task paused',
    placeholder: true,
    durationMs: 300,
  },
  task_blocked_01: {
    id: 'task_blocked_01',
    filePath: 'assets/office/sounds/task_blocked.wav',
    category: 'task_blocked',
    defaultVolume: 0.8,
    loop: false,
    priority: 'high',
    cooldownPolicyMs: 1000,
    maxSimultaneous: 1,
    accessibilityAlternative: 'Task is blocked and requires attention',
    placeholder: true,
    durationMs: 500,
  },
  task_failed_01: {
    id: 'task_failed_01',
    filePath: 'assets/office/sounds/task_failed.wav',
    category: 'task_failed',
    defaultVolume: 0.9,
    loop: false,
    priority: 'high',
    cooldownPolicyMs: 1000,
    maxSimultaneous: 1,
    accessibilityAlternative: 'Task failed',
    placeholder: true,
    durationMs: 600,
  },
  approval_requested_01: {
    id: 'approval_requested_01',
    filePath: 'assets/office/sounds/approval_requested.wav',
    category: 'approval_requested',
    defaultVolume: 0.8,
    loop: false,
    priority: 'high',
    cooldownPolicyMs: 2000,
    maxSimultaneous: 1,
    accessibilityAlternative: 'Approval requested for task',
    placeholder: true,
    durationMs: 450,
  },
  notification_received_01: {
    id: 'notification_received_01',
    filePath: 'assets/office/sounds/notification_received.wav',
    category: 'notification_received',
    defaultVolume: 0.5,
    loop: false,
    priority: 'low',
    cooldownPolicyMs: 300,
    maxSimultaneous: 3,
    accessibilityAlternative: 'New notification',
    placeholder: true,
    durationMs: 200,
  },
  agent_selected_01: {
    id: 'agent_selected_01',
    filePath: 'assets/office/sounds/agent_selected.wav',
    category: 'agent_selected',
    defaultVolume: 0.6,
    loop: false,
    priority: 'low',
    cooldownPolicyMs: 200,
    maxSimultaneous: 1,
    accessibilityAlternative: 'Agent selected',
    placeholder: true,
    durationMs: 150,
  },
  room_transition_01: {
    id: 'room_transition_01',
    filePath: 'assets/office/sounds/room_transition.wav',
    category: 'room_transition',
    defaultVolume: 0.4,
    loop: false,
    priority: 'low',
    cooldownPolicyMs: 1000,
    maxSimultaneous: 1,
    accessibilityAlternative: 'Transitioned to new room',
    placeholder: true,
    durationMs: 350,
  },
  system_warning_01: {
    id: 'system_warning_01',
    filePath: 'assets/office/sounds/system_warning.wav',
    category: 'system_warning',
    defaultVolume: 0.9,
    loop: false,
    priority: 'high',
    cooldownPolicyMs: 3000,
    maxSimultaneous: 1,
    accessibilityAlternative: 'System warning',
    placeholder: true,
    durationMs: 700,
  },
  emergency_stop_01: {
    id: 'emergency_stop_01',
    filePath: 'assets/office/sounds/emergency_stop.wav',
    category: 'emergency_stop',
    defaultVolume: 1.0,
    loop: false,
    priority: 'critical',
    maxSimultaneous: 1,
    accessibilityAlternative: 'EMERGENCY STOP TRIGGERED',
    placeholder: true,
    durationMs: 1000,
  },
};
