import { OFFICE_SCHEMA_VERSION, OFFICE_SOURCE_HEIGHT, OFFICE_SOURCE_WIDTH } from '../office/constants';
import { OfficeOverlayDocument } from '../office/types';
import { assertValidOverlayDocument } from '../office/validation';
export { INITIAL_AGENTS, OFFICE_LOCATIONS, WAYPOINTS } from './legacySimulationSeed';

/**
 * Development-only interaction fixture. Coordinates are illustrative and are
 * not traced from production markup. Never promote this document to production.
 */
const sampleOverlay: OfficeOverlayDocument = {
    schemaVersion: OFFICE_SCHEMA_VERSION,
    source: { width: OFFICE_SOURCE_WIDTH, height: OFFICE_SOURCE_HEIGHT },
    production: false,
    entities: [
        {
            id: 'sample.room.central',
            type: 'room',
            name: 'Sample room — not production',
            geometry: { kind: 'polygon', points: [{ x: 2650, y: 1450 }, { x: 5550, y: 1450 }, { x: 5700, y: 3820 }, { x: 2500, y: 3820 }] },
            sourceLayer: 'rooms',
            enabled: true,
            interactive: true,
            metadata: { fixture: true },
            zIndex: 0,
            tags: ['sample', 'non-production'],
            accessPolicy: { state: 'green' },
        },
        {
            id: 'sample.path.central',
            type: 'walk_path',
            name: 'Sample main path',
            geometry: { kind: 'polyline', points: [{ x: 1100, y: 2730 }, { x: 4096, y: 2730 }, { x: 7000, y: 2730 }], width: 180 },
            sourceLayer: 'paths',
            enabled: true,
            interactive: true,
            metadata: { fixture: true },
            zIndex: 0,
            tags: ['sample'],
            path: {
                nodeIds: ['sample.node.west', 'sample.node.center', 'sample.node.east'],
                linkedIntersectionIds: ['sample.node.center'],
                linkedRoomIds: ['sample.room.central'],
                linkedDoorIds: ['sample.door.central'],
                direction: 'bidirectional',
                blocked: false,
            },
            linkedEntityIds: ['sample.room.central', 'sample.door.central'],
        },
        {
            id: 'sample.wall.north',
            type: 'wall',
            name: 'Sample north wall',
            geometry: { kind: 'polyline', points: [{ x: 2650, y: 1450 }, { x: 5550, y: 1450 }], width: 36 },
            sourceLayer: 'walls',
            enabled: true,
            interactive: true,
            metadata: { fixture: true },
            zIndex: 0,
            parentId: 'sample.room.central',
        },
        {
            id: 'sample.door.central',
            type: 'door',
            name: 'Sample reserved door',
            geometry: { kind: 'rectangle', rect: { x: 3980, y: 1410, width: 230, height: 80 } },
            sourceLayer: 'doors',
            enabled: true,
            interactive: true,
            metadata: { fixture: true },
            zIndex: 5,
            accessState: 'blue',
            accessPolicy: { state: 'blue', roleIds: ['sample.role'] },
            linkedEntityIds: ['sample.room.central'],
            door: {
                currentState: 'blue',
                defaultState: 'green',
                linkedRoomIds: ['sample.room.central'],
                reservedGroupIds: ['sample.group'],
                scheduleReference: 'future-schedule-id',
                locked: false,
                visualState: 'closed',
            },
        },
        {
            id: 'sample.desk.priority',
            type: 'desk',
            name: 'Sample priority desk',
            geometry: { kind: 'rectangle', rect: { x: 3400, y: 2150, width: 620, height: 360 } },
            sourceLayer: 'furniture',
            enabled: true,
            interactive: true,
            metadata: { fixture: true },
            zIndex: 0,
            seatPriority: 'yellow',
            parentId: 'sample.room.central',
        },
        {
            id: 'sample.computer.one',
            type: 'computer',
            name: 'Sample computer',
            geometry: { kind: 'rectangle', rect: { x: 3580, y: 2170, width: 220, height: 120 } },
            sourceLayer: 'computers',
            enabled: true,
            interactive: true,
            metadata: { fixture: true },
            zIndex: 0,
            parentId: 'sample.desk.priority',
        },
        {
            id: 'sample.light.access',
            type: 'access_light',
            name: 'Sample meeting reservation light',
            geometry: { kind: 'point', point: { x: 4250, y: 1425 } },
            sourceLayer: 'lights',
            enabled: true,
            interactive: true,
            metadata: { fixture: true },
            zIndex: 0,
            accessState: 'yellow',
            parentId: 'sample.door.central',
        },
        {
            id: 'sample.restricted.east',
            type: 'restricted_zone',
            name: 'Sample blocked zone',
            geometry: { kind: 'polygon', points: [{ x: 5000, y: 1800 }, { x: 5480, y: 1800 }, { x: 5480, y: 2350 }, { x: 5000, y: 2350 }] },
            sourceLayer: 'restricted',
            enabled: true,
            interactive: true,
            metadata: { fixture: true },
            zIndex: 0,
            accessState: 'red',
            accessPolicy: { state: 'red' },
            parentId: 'sample.room.central',
        },
        {
            id: 'sample.effect.hologram-glow',
            type: 'effect_zone',
            name: 'Sample hologram glow',
            geometry: { kind: 'polygon', points: [{ x: 3820, y: 3100 }, { x: 4380, y: 3100 }, { x: 4480, y: 3650 }, { x: 3720, y: 3650 }] },
            sourceLayer: 'effects',
            enabled: true,
            interactive: false,
            metadata: { fixture: true },
            zIndex: 0,
        },
        {
            id: 'sample.sprite.hologram',
            type: 'sprite_anchor',
            name: 'Central blue tube hologram placeholder anchor',
            geometry: { kind: 'point', point: { x: 4096, y: 3375 } },
            sourceLayer: 'sprites',
            enabled: true,
            interactive: true,
            metadata: { fixture: true, missingAssetExpected: true },
            zIndex: 1,
            sprite: {
                assetId: 'central-blue-tube-hologram',
                animation: {
                    frameWidth: 128,
                    frameHeight: 192,
                    frameCount: 8,
                    columns: 8,
                    frameSequence: [0, 1, 2, 3, 4, 5, 6, 7],
                    frameDurationMs: 120,
                    loop: true,
                    pingPong: true,
                    idle: true,
                },
                scale: 2,
                opacity: 0.9,
                glow: '#35c7ff',
                blendMode: 'screen',
                pointerEvents: false,
            },
        },
        {
            id: 'sample.interaction.focus',
            type: 'interaction_zone',
            name: 'Sample focus target',
            geometry: { kind: 'rectangle', rect: { x: 3720, y: 3050, width: 760, height: 700 } },
            sourceLayer: 'hitboxes',
            enabled: true,
            interactive: true,
            metadata: { fixture: true },
            zIndex: 0,
            linkedEntityIds: ['sample.sprite.hologram'],
        },
        {
            id: 'sample.label.central',
            type: 'label_anchor',
            name: 'Sample Central Room',
            geometry: { kind: 'point', point: { x: 4096, y: 1700 } },
            sourceLayer: 'labels',
            enabled: true,
            interactive: false,
            metadata: { fixture: true },
            zIndex: 0,
            parentId: 'sample.room.central',
        },
    ],
    pathNodes: [
        { id: 'sample.node.west', point: { x: 1100, y: 2730 }, connectedNodeIds: ['sample.node.center'] },
        { id: 'sample.node.center', point: { x: 4096, y: 2730 }, connectedNodeIds: ['sample.node.west', 'sample.node.east'] },
        { id: 'sample.node.east', point: { x: 7000, y: 2730 }, connectedNodeIds: ['sample.node.center'] },
    ],
};

export const NON_PRODUCTION_OVERLAY = assertValidOverlayDocument(sampleOverlay);
